language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
  
before_install:
  - sudo apt-get build-dep python3-numpy python3-scipy python-matplotlib
  
# command to install dependencies
install:  
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  - pip install -r requirements.txt
# command to run tests
script: pytest 
