language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - graphviz

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib pytest
  #- python setup.py install
  - pip install -r requirements.txt

#before_install:
#  - pip install --upgrade pip setuptools wheel

# command to install dependencies
#install:  
#  - pip install -U pytest

#  - pip install -r requirements.txt
  
# command to run tests
script: cd tests && pytest 
